## These functions return the inverse of an invertible matrix
## (do not check if the matrix is invertible). If the inverse matrix
## has never been calculated, these functions calculate it.
## If the inverse matrix have already been calculated, the function
## returns the variable where the inverse matrix is stored. 

## This function returns a list of 4 items using an invertible
## matrix as argument. These elements are functions. The first 
## function introduces a new matrix as an argument and removes the
## inverted matrix previously calculated. The second function returns
## the matrix introduced as an argument. The third functions introduces
## the inverse matrix of the argument in the variable and the fourth
## returns the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
        s <- NULL
        set <- function(y) {
                x <<- y
                s <<- NULL
        }
        get <- function() x
        setsolve <- function(solve) s <<- solve
        getsolve <- function() s
        list(set = set, get = get,
             setsolve = setsolve,
             getsolve = getsolve)
}


## This function checks if the list generated by the function
## makeCacheMatrix contains the inverse matrix  requested. If so,
## this variable is returned. If not calculate the inverse matrix.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        s <- x$getsolve()
        if(!is.null(s)) {
                message("getting cached data")
                return(s)
        }
        data <- x$get()
        s <- solve(data, ...)
        x$setsolve(s)
        s
}
